### ISSUE TITLE
ModeDetector.InUnitTestRunner is wrong for my .net mstest assembly

### ISSUE THREAD

**Issue by automatonic** [paulcbetts/splat#115]
I was having issues with a ReactiveList complaining about there being no dispatcher on the current thread. After digging a bit, I checked to see how ReactiveUI was deciding what schedulers to use for unit testing. That lead me to splat. The below test fails:
```
[TestMethod]
 public void ShouldBeInUnitTestRunner()
 {
         ModeDetector.InUnitTestRunner().Should().BeTrue("this is a unit test");
 }
```

This is a full framework WPF application running against .NET 4.5.2, and i am using mstest for my test assembly.

My question~~s~~:
1. Why might splat be getting this wrong?
~~2. How can i find out what implementation is selected in my case?~~
~~3. Where do i find the code for that implementation...is that a separate nuget package?~~

**Comment by automatonic** [comment]
I am assuming PlatformModeDetector is what is running.

**Comment by automatonic** [comment]
OK...so it would appear that "Microsoft.VisualStudio.QualityTools.UnitTestFramework" would not be matched. Guess I could just roll my own.

**Comment by paulcbetts** [comment]
@automatonic Can you send in a PR to fix it instead?

**Comment by automatonic** [comment]
yep.
