### ISSUE TITLE
Method ToNative() does not recognize?

### ISSUE THREAD

**Issue by poseydonfba** [paulcbetts/splat#151]
When I use the ToNative() method it does not recognize. Any idea why this is happening?

Info:

Xamarin Forms Prism

Splat version 1.6.0

using Splat;

![image](https://cloud.githubusercontent.com/assets/9142662/26058446/4b9374e0-3954-11e7-8363-701ef8236ed2.png)

**Comment by poseydonfba** [comment]
As I understand it, ToNative() can not be used within PCL Portable projects.

I am using the code below the Akavache to cache images.

Return is an IBitmap, how can I convert this IBitmap to an ImageSource? It's possible?


```
var url = "https://ashdbhjas/image.png";

            BlobCache.LocalMachine.LoadImageFromUrl(url).Subscribe(image =>
            {
                ImageSource myimg = image; // ???				
            });
```

**Comment by Cheesebaron** [comment]
ToNative implies there is a Native implementation, meaning that you are _on_ a native platform.

You actually answered your question yourself: "How can I convert this IBitmap to an ImageSource". How about, using a ValueConverter for your binding?

**Comment by poseydonfba** [comment]
Hi, I had to use it this way:

var url = "https://ashdbhjas/image.png";
var img = await BlobCache.LocalMachine.LoadImageFromUrl(url); 

```
MemoryStream imageStream = new MemoryStream();

await imageSrc.Save(CompressedBitmapFormat.Jpeg, 1.0f, imageStream);

stream.Position = 0;
var imageSrc = ImageSource.FromStream(() => imageStream);
```

http://stackoverflow.com/questions/43986570/loadimagefromurl-ibitmap-to-imagesource/43989038#43989038
