### ISSUE TITLE
Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259',

### ISSUE THREAD

**Issue by RenjithPr90** [paulcbetts/splat#154]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by ghuntley** [comment]
Please use Splat 1.6.2 when targeting PCL projects. v2.0 and onwards is netstandard only. There will be no updates to the 1.6.x series so if you need to patch the release then please fork and maintain your own copy/build from source. See also #149

**Comment by EmilAlipiev** [comment]
@ghuntley I dont understand one thing, I have an existing project with 2.0 using Profile259 and it works fine but I created a new project using Profile259, it doesnt install. what is my deal do you think?

**Comment by EmilAlipiev** [comment]
this is how my Projet targets looks like 

![image](https://user-images.githubusercontent.com/10422347/31628110-f6f234e6-b2af-11e7-8111-9febd88f97a3.png)

and all projects are update using only nuget

![image](https://user-images.githubusercontent.com/10422347/31628205-435449d2-b2b0-11e7-8292-8f8b7fb0c9e0.png)

it works like a charm on this project. I dont know how and why if you say it is not meant to be for Profile259
