### ISSUE TITLE
Could not find a default bitmap loader. 

### ISSUE THREAD

**Issue by HarryMcCarney** [paulcbetts/splat#57]
"This should never happen, your dependency resolver is broken"

I am not using a dependency resolver. Shouldn't the library be resolving this for me. 
Have i missed something?
The calling code is in a test.

**Comment by Lug16** [comment]
Hi,

Could you please explain how to do that, I'm facing the same situation.

Thank you very much

**Comment by TobiasBuchholz** [comment]
Updating Splat from 1.4.0 to 1.6.2 solved the problem for me.

**Comment by shiftkey** [comment]
Closing this out as resolved (eventually).

**Comment by EmilAlipiev** [comment]
I am seeing this error for 2.0 version. It occurs for android 7 and higher but works fine earlier versions. my simple usage is 
```

  string ImageUri = "sample.png";

 var Image = await Splat.BitmapLoader.Current.LoadFromResource(ImageUri, null, null);
```

Can you please advise something?

**Comment by ghuntley** [comment]
@EmilAlipiev  can you please open a new issue and attach a repro/test application. Ta

**Comment by EmilAlipiev** [comment]
@ghuntley  it looks like that it appears only in release mode in xamarin.android when using full linking. I added splat into skipped assemblies and it works fine now
