### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by martinsmyllie** [paulcbetts/splat#89]
Hi, 

I am writing a PCL making use of Splat System.Drawing.Color.

I am unit testing it in a .NET 4.5.1 test project. In my test method I initialize a test color so have a reference to the .NET Framework System.Drawing assembly in my test project as well as Splat 1.6.0.0 ( the .NET 4.5 version)

When my test goes into my PCL method and tries to construct a color I get the following Exception:

System.MissingMethodException Method not found: 'System.Drawing.Color System.Drawing.Color.FromKnownColor(System.Drawing.KnownColor)'. 

Have I done something wrong? or is this a bug?

**Comment by paulcbetts** [comment]
No idea, that seems weird, is there any reason in particular you're targeting 4.5.1?

**Comment by martinsmyllie** [comment]
Hi Paul,

No particular reason for 4.5.1 - just using latest .NET framework for ease
of unit testing.

I'm also referencing Akavache... which has a Splat dependency too, in case
that's of any relevance

I'm just figuring out how Splat is supposed to work as the Splat 1.6
assembly in my unit test bin folder is (obviously) targeting .NET 4.5 and
does not have a System.Drawing namespace in it.

I guess this is as expected... but I'm a bit puzzled as to how my PCL code
is supposed to pick up the correct reference in this scenario... also I'm
wondering why it would be a MethodNotFound
exception as opposed to a TypeNotFound exception.... it kind of implies
that it found a System.Drawing.Color type, but just not the method.


Martin

**Comment by paulcbetts** [comment]
@martinsmyllie What is the assembly version of the Splat in your PCL and the Splat in your unit test?

**Comment by martinsmyllie** [comment]
The PCL is referencing Splat 1.6.0.0
The unit test assembly is also referencing Splat 1.6.0.0

and I've checked in my x86\Debug folder after building the unit tests and I have Splat 1.6 which when looked at with ildasm shows only types in the Splat namespace.

Also looking at the assembly manifest it contains the System Drawing redirects.

.class extern forwarder System.Drawing.Color
{
  .assembly extern System.Drawing
}

**Comment by martinsmyllie** [comment]
Actually having read the mainfest some more is the issue that the KnownColor enum is not forwarded.

Should the manifest have the following?

.class extern forwarder System.Drawing.KnownColor
{
.assembly extern System.Drawing
}

**Comment by martinsmyllie** [comment]
Hi Paul,
I've pulled the source and tested out this theory, which is correct, and fixed it so everything is working now.

I've added the appropriate line to TypeForwardedSystemDrawing.cs, and created a Commit, but I can't sync it back to the project because I don't have permission.

Could you let me know what I need to do.

Thanks,

Martin

**Comment by paulcbetts** [comment]
@martinsmyllie Please do!

**Comment by martinsmyllie** [comment]
Done

**Comment by kentcb** [comment]
Fixed by #90
