### ISSUE TITLE
System.Drawing.Color no longer available in Xamarin.Mac 1.12.x+

### ISSUE THREAD

**Issue by DennisWelu** [paulcbetts/splat#91]
Using splat on the beta channel of Xamarin right now with Unified Xamarin.Mac 1.12.0.4 and Color is no longer an understood reference. Note that it IS available on the stable channel (1/29/15) Unified Xamarin.Mac 1.10.0.18. But Xamarin support says this was removed in 1.12 as part of the ongoing transition of the Mac stuff to Unified.

I think the fix may be to include the Colors folder into the Splat-XamarinMac project. But then Splat will not build due to the TypeForwardedTo's in TypeForwardedSystemDrawing.cs. Could change the preprocessor logic there to "#if !UNIFIED" but that raises the larger question of all the places where "#if UIKIT" kinds of things are going on. Maybe they all should be just based on UNIFIED going forward, not sure yet.

**Comment by paulcbetts** [comment]
@DennisWelu Just remove the TypeForwardedSystemDrawing.cs file from the Xam Mac 64-bit's csproj file

**Comment by DennisWelu** [comment]
@paulcbetts That works too, although there are other TypeForwardedTo's in that file for Point, PointF, Rectangle, etc.. The Xam iOS csproj still has that file and I'm wondering why they wouldn't be the same under the new Unified roof.

**Comment by paulcbetts** [comment]
This is fixed in the latest version
