### ISSUE TITLE
Can this library compress images?

### ISSUE THREAD

**Issue by robertbird** [paulcbetts/splat#93]
As well as resizing images, is there a way to reduce the quality or change the quality setting that is used when resizing? (i.e. if it is a JPEG)

I am looking for a way to shrink the photos taken with the camera before sending to my API. I've seen several libraries that shrink photos and some that compress them, but so far haven't seen any that do both, 

This library looks very full featured, but I couldn't see how to do this. Or maybe I'm missing the point here and compression is not really needed?

Cheers,
Rob

**Comment by paulcbetts** [comment]
`IBitmapImage.Save` does this, it will save as either PNG or JPEG and does let you set compression levels on JPEG
