### ISSUE TITLE
IBitmap Windows Phone 8.1 memory issues

### ISSUE THREAD

**Issue by promontis** [paulcbetts/splat#96]
Hi Paul,

I'm so sorry for asking you this, since I know how much you *love* this platform, but I was wondering how are you using IBitmap. Let me explain how I tried using it and where it goes wrong.

I began with using Akavache to load an IBitmap in my view model from the cache using an url. This works, no problem. The image loads from the cache (and again from the web) and is displayed on the screen. But when my ListView is starting to get a lot of images, it crashed due to an OutOfMemoryException. 

I tried detecting a potential memory leak; the WriteableBitmaps seems not to be released. So, I tried disposing them manually when the image goes out of the visual area, but disposing the IBitmap actually means that the stream is closed, and when you scroll back so that the image is visible again, there is no image loaded. Makes sense. So, disposing the image doesn't seem to work if you need to show (reload) the image again.

I tried implementing some data virtualization so that it only loads items visible and disposed those who are not, but Windows Phone is really vague here; you need to implement some weird interface, which isn't described in detail anywhere, nor anyone has an implementation. So, that's not an option as well.

Back to the OutOfMemoryException... the IBitmap is loaded in my viewmodel. When I don't show the image on screen, but just load it, I do run out of memory. So even just loading it, and keeping it in memory, is a problem. When I load it, and then immediately dispose it, the memory is stable again. 

So, should I actually load the IBitmap in my viewmodel in the first place? It seems that this is not the way to go. But if I don't, what's the use of having a xplat bitmap implementation?

**Comment by promontis** [comment]
Using a value converter which gets the bitmap from akavache, convert it to a stream and set it as a source, seems to work :) yeay!!! Took me 5 days to figure this out!

The stream/bytes seems to be only referenced by the listviewitem (not the viewmodel) and thus when UI virtualization removes that listviewitem, it disposes the stream/bytes! Memory is stable now


```
 public class SplatBitmapConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            if (value == null)
            {
                return null;
            }

            var bitmap = new BitmapImage();

            BlobCache.LocalMachine.LoadImageFromUrl((string)value).Subscribe(picture =>
            {
                CoreApplication.MainView.CoreWindow.Dispatcher.RunAsync(
                    CoreDispatcherPriority.Normal, async () =>
                    {
                        var stream = new MemoryStream();
                        await picture.Save(CompressedBitmapFormat.Jpeg, 1.0f, stream);
                        stream.Seek(0, SeekOrigin.Begin);
                        await bitmap.SetSourceAsync(WindowsRuntimeStreamExtensions.AsRandomAccessStream(stream));
                    });
               
            });

            return bitmap;
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotSupportedException();
        }
    }
```

**Comment by paulcbetts** [comment]
@promontis Cool, glad it works!
